apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample-microservice
  template:
    metadata:
      labels:
        app: go-sample-microservice
    spec:
      containers:
        - name: go-sample-microservice
          image: go-sample-microservice:0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace