apiVersion: v1
kind: Service
metadata:
  name: go-sample-microservice
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: go-sample-microservice
  internalTrafficPolicy: Local