apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-sample-microservice
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
      - cluster: production
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-go-sample-microservice'
    spec:
      project: example-application
      source:
        repoURL: https://github.com/font3r/argocd-sandbox
        targetRevision: HEAD
        path: deploy/overlays/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: example-project-{{.cluster}}